### ISSUE TITLE
odoc: internal error, uncaught exception (with ocaml-containers)

### ISSUE THREAD

**Issue by Fourchaux** [ocaml-doc/odoc#103]
( OCaml 4.06.1+rc1 - odoc 1.2.0)

Trying $ make doc
with https://github.com/c-cube/ocaml-containers
display these errors :

.....
odoc _doc/containers/CCArray.odoc (exit 2)
(cd _build/default/_doc/containers ...)
odoc: internal error, uncaught exception:
      File "src/docOckIdentEnv.ml", line 260, characters 22-28: Assertion failed
      
odoc _doc/containers/CCArrayLabels.odoc (exit 2)
(cd _build/default/_doc/containers ...)
odoc: internal error, uncaught exception:
      File "src/docOckIdentEnv.ml", line 260, characters 22-28: Assertion failed

No more problem if the 2 following lines are commented :

https://github.com/c-cube/ocaml-containers/blob/master/src/core/CCArray.mli#L16

https://github.com/c-cube/ocaml-containers/blob/master/src/core/CCArrayLabels.mli#L16

**Comment by trefis** [comment]
This is now fixed.

**Comment by Fourchaux** [comment]
Sorry but: 

After doing 
```$ opam pin add odoc --dev-repo```

(and trying with OCaml 4.06.0+flambda or 4.06.1+flambda)

$ make doc 
still fails (with the same messages).

**Comment by dbuenzli** [comment]
@Fourchaux you have to pin doc-ock.

**Comment by Fourchaux** [comment]
Thank you  @dbuenzli. Problem solved.

**Note:** 
Dans le monde OCaml ,pour que les choses marchent, il faut d'abord se masturber puis pas mal piner je trouve. 
Disons que ça occupe durant ces froides périodes hivernales ...
